export const GITHUB_ACTIONS_TYPES = {
  GET_USERS: "GET_USERS",
  SET_LOADING: "SET_LOADING",
  CLEAR_SEARCH: "CLEAR_SEARCH",
  GET_USER: "GET_USER",
  GET_REPOS: "GET_REPOS",
  GET_USER_AND_REPOS: "GET_USER_AND_REPOS",
};
